# test 용 설정 (테스트 - 포트 필요 없음)
spring:
  # 데이터 베이스 설정
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    user: sa
    password:

  # JPA 설정
  jpa:
    properties:
      hibernate:
        show_sql: true # 실행하는 SQL을 콘솔에 출력 (true)
        format_sql: true # 실행되는 SQL의 들여쓰기 및 줄 개행 기능 (true)
        use_sql_comments: true
        #dialect: org.hibernate.dialect.OracleDialect - 이전 버전 : dialect 설정 필수!
    hibernate:
      ddlAuto: create # 테이블 자동 생성

# 로거 설정 (설정 추가 -> level: 하위에 넣으면 됨)
logging:
  level:
    org:
      hibernate:
        type: trace

